### ISSUE TITLE
GISystem出荷実績出力機能追加要望

### ISSUE THREAD

**Issue by jms-funato** [jms-web/SRS.F#14]
### 依頼元と請求先
西川物産殿からの依頼ですが、請求は新立産業へ(新立産業殿が西川物産との間で費用調整されるそうです)

#### データソース：tblsyukka SK0090="N" join tbljuchu on SK0020 = JU0010
-  納入日 syukkaから取得
- 受注No(受注SEQ)　syukkaから取得
- 品番(得意先品番) juchuから取得
- 品名(得意先品名) juchuから取得
- 数量 syukkaから取得

### タスク
- [x] 見積作成-新立産業 石田様に送信
	見積は富士松と碧南で分ける
- PG実装
	- [x] 新立産業 飯野様にSMTPメールサーバ情報を確認
	- [x] CSV作成処理実装(元データ・・・tblSyukka:出荷実績データ)
	- [x] メール送信処理実装
参考Link
[MS CDO](http://chee-s.net/access%E3%81%AEvba%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%A1%E3%83%BC%E3%83%AB%E3%82%92%E7%9B%B4%E6%8E%A5%E9%80%81%E4%BF%A1%EF%BD%9Emicrosft-cdo%E7%B7%A8%EF%BD%9E)
[BASP21](http://www.hi-ho.ne.jp/~babaq/basp21.html)
[BASP21 SendMail](http://officetanaka.net/excel/vba/tips/tips45.htm)
	- [x] 受注エラーリストチェックに品名サイズオーバーの項目を追加
	~- [ ] CSVフォーマット資料作成~ 西川物産から依頼があれば作成
	- [x] 現地環境動作テスト

### 処理内容
1. GIsystemに出荷実績データ送信ボタンを追加
1. ↑ボタンクリック時に、出荷実績データCSVファイルをSendフォルダ(送信待ちフォルダ)に出力し、
西川物産担当者(+CCで新立産業 担当者)宛にメール送信

![image](https://user-images.githubusercontent.com/20087685/41758419-77d94d9c-7623-11e8-9521-17767eb40ed5.png)

### MDBの場所
\\\JMSSRV2\DEV\新立産業\PGM\SRSGISystemNB\SRSGISystemF.mdb

### GIsystem テーブル仕様書
\\\fukuta-pc2016\DEV\豊商運\西川ゴムGIシステム\【テーブル定義書】ゴムノイナキ㈱受注出荷管理システム\05.08.04【テーブル定義書】ゴムノイナキ受注出荷管理システム（新立産業）.xls

**Comment by jms-funato** [comment]
@jms-fukuta 
送信元(新立産業担当者)のメール情報は下記の場所に置いてあります。
\\\JMSSRV2\DEV\新立産業\PGM\SRSGISystemNB\メール送信設定.txt

ちなみにJMSのメールサーバ(シーサイドメール)の情報は、
\\\JMSSRV2\TOOL\CsideMail\Info.txtにおいてあります。
送信テストをする場合は参考にして下さい。

**Comment by jms-funato** [comment]
### メール送信先
#### 富士松
- To
西川物産 中元 <c-nakamoto@nishikawa-rbr.co.jp>
- CC
西川物産 堂官部長 <a-doukan@nishikawa-rbr.co.jp>
西川物産 田村課長 <ta-tamura@nishikawa-rbr.co.jp>
新立産業 石田常務 <srs-ishida@katch.ne.jp>

#### 碧南
西川物産への送信先は富士松と同じ？

**Comment by jms-fukuta** [comment]
**＜PG変更点＞**
１．画面に出荷データ送信ボタンを追加
![image](https://user-images.githubusercontent.com/37360243/42068236-bd825494-7b85-11e8-905c-0cd352aa833d.png)

２．クエリー：q_出荷実績データを追加
３．Form_frmMainプロジェクトに以下の関数追加
　①cmdSend_S_Click
　②Mail_Send
　③SendMailByCDO
４．納入時に必要な設定変更内容
　①Mail_Send関数内の「★★★設定値★★★」セクションの
　　SMTPサーバー：mail.katch.ne.jp
　　MailFrom：srs-takeda@katch.ne.jp
　　MailTo：c-nakamoto@nishikawa-rbr.co.jp
　　MailCC：a-doukan@nishikawa-rbr.co.jp;ta-tamura@nishikawa-rbr.co.jp;srs-ishida@katch.ne.jp;
　②テーブル：tblSyukkaのSK0090フィールドの既存データの'N'を'Y'に６月以前の出荷分のデータを更新
　　⇒ update tblSyukka set SK0090 = 'Y' WHERE SK0070 < '20180701000000'
　③必要であれば、cmdSend_S_Clickの★★★送信先フォルダ★★★セクションのパスを変更

５．送信データのメール送信後のバックアップ先は「C:\SRSGISystemNB\Send\Back」となる

**Comment by jms-funato** [comment]
SMTP認証情報他のパラメータの追加が必要だった
http://serialty.blog117.fc2.com/blog-entry-10.html

**Comment by jms-funato** [comment]
#### 納入日の出力項目を変更
```tblSyukka.SK0070 -> tblJuchu.JU0070```
